// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "CustomTitle.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class CustomTitle
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v18.01.00
// App/Edition: app-test-pickers/
// User:        2sichost
// When:        2024-09-24 13:04:01Z
namespace AppCode.Data
{
  // This is a generated class for CustomTitle 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// CustomTitle data. <br/>
  /// Generated 2024-09-24 13:04:01Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.InternalTitle`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class CustomTitle: AutoGenerated.ZAutoGenCustomTitle
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.CustomTitle in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenCustomTitle: Custom.Data.CustomItem
  {
    /// <summary>
    /// InternalTitle as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("InternalTitle", scrubHtml: true) etc.
    /// </summary>
    public string InternalTitle => _item.String("InternalTitle", fallback: "");

    /// <summary>
    /// More as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("More", scrubHtml: true) etc.
    /// </summary>
    public string More => _item.String("More", fallback: "");

    /// <summary>
    /// Title as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Title", scrubHtml: true) etc.
    /// </summary>
    /// <remarks>
    /// This hides base property Title.
    /// To access original, convert using AsItem(...) or cast to ITypedItem.
    /// Consider renaming this field in the underlying content-type.
    /// </remarks>
    public new string Title => _item.String("Title", fallback: "");
  }
}