// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "OldEntityQueriesDifferentSources.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class OldEntityQueriesDifferentSources
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v18.01.00
// App/Edition: app-test-pickers/
// User:        2sichost
// When:        2024-09-24 13:04:01Z
namespace AppCode.Data
{
  // This is a generated class for OldEntityQueriesDifferentSources 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// OldEntityQueriesDifferentSources data. <br/>
  /// Generated 2024-09-24 13:04:01Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.BikeSource`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class OldEntityQueriesDifferentSources: AutoGenerated.ZAutoGenOldEntityQueriesDifferentSources
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.OldEntityQueriesDifferentSources in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenOldEntityQueriesDifferentSources: Custom.Data.CustomItem
  {
    /// <summary>
    /// BikeSource as single item of Bike.
    /// </summary>
    /// <remarks>
    /// Generated to only return 1 child because field settings had Multi-Value=false. The type Bike was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// A single item OR null if nothing found, so you can use ?? to provide alternate objects.
    /// </returns>
    public Bike BikeSource => _bikeSource ??= _item.Child<Bike>("BikeSource");
    private Bike _bikeSource;

    /// <summary>
    /// CarSource as single item of Car.
    /// </summary>
    /// <remarks>
    /// Generated to only return 1 child because field settings had Multi-Value=false. The type Car was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// A single item OR null if nothing found, so you can use ?? to provide alternate objects.
    /// </returns>
    public Car CarSource => _carSource ??= _item.Child<Car>("CarSource");
    private Car _carSource;
  }
}