// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "OldStringDropdowns.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class OldStringDropdowns
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v18.01.00
// App/Edition: app-test-pickers/
// User:        2sichost
// When:        2024-09-24 13:04:01Z
namespace AppCode.Data
{
  // This is a generated class for OldStringDropdowns 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// OldStringDropdowns data. <br/>
  /// Generated 2024-09-24 13:04:01Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.EmptyShouldPreselect`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class OldStringDropdowns: AutoGenerated.ZAutoGenOldStringDropdowns
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.OldStringDropdowns in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenOldStringDropdowns: Custom.Data.CustomItem
  {
    /// <summary>
    /// EmptyShouldPreselect as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("EmptyShouldPreselect", scrubHtml: true) etc.
    /// </summary>
    public string EmptyShouldPreselect => _item.String("EmptyShouldPreselect", fallback: "");

    /// <summary>
    /// HavePreselectedLabel as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("HavePreselectedLabel", scrubHtml: true) etc.
    /// </summary>
    public string HavePreselectedLabel => _item.String("HavePreselectedLabel", fallback: "");

    /// <summary>
    /// HavePreselectedValue as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("HavePreselectedValue", scrubHtml: true) etc.
    /// </summary>
    public string HavePreselectedValue => _item.String("HavePreselectedValue", fallback: "");

    /// <summary>
    /// LabelValuesStringDropdown as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("LabelValuesStringDropdown", scrubHtml: true) etc.
    /// </summary>
    public string LabelValuesStringDropdown => _item.String("LabelValuesStringDropdown", fallback: "");

    /// <summary>
    /// MultipleItemsWithMINUSSeparator as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("MultipleItemsWithMINUSSeparator", scrubHtml: true) etc.
    /// </summary>
    public string MultipleItemsWithMINUSSeparator => _item.String("MultipleItemsWithMINUSSeparator", fallback: "");
  }
}