// DO NOT MODIFY THIS FILE - IT IS AUTO-GENERATED
// See also: https://go.2sxc.org/copilot-data
// To extend it, create a "VehicleParentChild.cs" with this contents:
/*
namespace AppCode.Data
{
  public partial class VehicleParentChild
  {
    // Add your own properties and methods here
  }
}
*/

// Generator:   CSharpDataModelsGenerator v18.01.00
// App/Edition: app-test-pickers/
// User:        2sichost
// When:        2024-09-24 13:04:01Z
namespace AppCode.Data
{
  // This is a generated class for VehicleParentChild 
  // To extend/modify it, see instructions above.

  /// <summary>
  /// VehicleParentChild data. <br/>
  /// Generated 2024-09-24 13:04:01Z. Re-generate whenever you change the ContentType. <br/>
  /// <br/>
  /// Default properties such as `.Title` or `.Id` are provided in the base class. <br/>
  /// Most properties have a simple access, such as `.Children`. <br/>
  /// For other properties or uses, use methods such as
  /// .IsNotEmpty("FieldName"), .String("FieldName"), .Children(...), .Picture(...), .Html(...).
  /// </summary>
  public partial class VehicleParentChild: AutoGenerated.ZAutoGenVehicleParentChild
  {  }
}

namespace AppCode.Data.AutoGenerated
{
  /// <summary>
  /// Auto-Generated base class for Default.VehicleParentChild in separate namespace and special name to avoid accidental use.
  /// </summary>
  public abstract class ZAutoGenVehicleParentChild: Custom.Data.CustomItem
  {
    /// <summary>
    /// Children as single item of VehicleParentChild.
    /// </summary>
    /// <remarks>
    /// Generated to only return 1 child because field settings had Multi-Value=false. The type VehicleParentChild was specified in the field settings.
    /// </remarks>
    /// <returns>
    /// A single item OR null if nothing found, so you can use ?? to provide alternate objects.
    /// </returns>
    public VehicleParentChild Children => _children ??= _item.Child<VehicleParentChild>("Children");
    private VehicleParentChild _children;

    /// <summary>
    /// Name as string. <br/>
    /// For advanced manipulation like scrubHtml, use .String("Name", scrubHtml: true) etc.
    /// </summary>
    public string Name => _item.String("Name", fallback: "");
  }
}